CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    EMPLOYEE_ID INT(10) NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    MIDDLE_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    DATE_OF_JOINING DATE NOT NULL,
    DATE_OF_LEAVING DATE,
    DEPARTMENT VARCHAR(20),
    DESIGNATION VARCHAR(20),
    CREATED_BY INT(10) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    MODIFIED_BY INT(10),
    MODIFIED_ON TIMESTAMP,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY(CREATED_BY) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE,
    FOREIGN KEY(MODIFIED_BY) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);